export const TextContent = {
  head: 'Notions',
  notion1: 'Props',
  notion2: 'Handling events',
  notion3: 'Map',
  notion4: 'Filter & Map',
  notion5: 'State',
  notion6: 'Lift the State',
  notion7: 'Axios',
  notion8: 'Context',
  notion9: 'Router Params',
  notion10: 'UseEffect',
  link1: 'https://github.com/clepirault/clepi-react-skills/blob/master/src/components/feature/checkbox/Checkbox.jsx',
  link2: 'https://github.com/clepirault/clepi-react-skills/blob/master/src/components/feature/ToDoList.jsx',
  link3: 'https://github.com/clepirault/clepi-react-skills/blob/master/src/components/context',
  link4: 'https://github.com/clepirault/clepi-react-skills/blob/master/src/components/feature/API',
  link5: 'https://github.com/clepirault/clepi-react-skills/blob/master/src/components/feature/API/APIItem.jsx',
};